### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by softBarbarian** [mcfarljw/cordova-plugin-apptentive#2]
Hello,
@mcfarljw I was wondering if you have plans to support iOS? If note hat do you thinks the work effort will be to support iOS?
Thanks a lot

**Comment by mcfarljw** [comment]
Not any immediate plans, but I'm probably going to do rewrites of some of my cordova plugins this summer. It'd be cool if the apptentive team would release an official cordova plugin, as they have a better understanding of how it works internally and it'd save us frustration :)

**Comment by msaffitz** [comment]
Hi @mcfarljw and @softBarbarian .  I'm pleased to report that an official Apptentive Cordova plugin is in the works and is expected to be released very shorty.  Stay tuned!   -- Mike (CTO @ Apptentive)

**Comment by mcfarljw** [comment]
Glad to hear it and thanks for mentioning it!
